CREATE DATABASE VaccinationDB;
USE VaccinationDB;
SET LANGUAGE us_english;

-- CREATION OF TABLES

CREATE TABLE DISEASE(
	id INT PRIMARY KEY IDENTITY,
	disease VARCHAR(75),
	dui_citizen CHAR(10) NOT NULL						--FK
);

CREATE TABLE CITIZEN(
	dui CHAR(10) PRIMARY KEY,
	fullName VARCHAR(75) NOT NULL,
	address VARCHAR(75) NOT NULL, 
	phone CHAR(9) NOT NULL, 
	email VARCHAR(50) NULL,
	id_identifer INT NOT NULL								--FK
);

CREATE TABLE IDENTIFIER(
	id INT PRIMARY KEY IDENTITY,
	identifier VARCHAR(50) NOT NULL
)

CREATE TABLE SIDE_EFFECT(
	id INT PRIMARY KEY IDENTITY,
	side_effect VARCHAR(75),
	id_vaccine INT NOT NULL								--FK
);

CREATE TABLE VACCINE(
	id INT PRIMARY KEY IDENTITY, 
	date DATE NOT NULL, 
	hour TIME NOT NULL,
	dose VARCHAR(25) NOT NULL,
	dui_citizen CHAR(10) NOT NULL,						--FK
	identifier_employee VARCHAR(50) NOT NULL			--FK
);

CREATE TABLE EMPLOYEE(
	identifier VARCHAR(50) PRIMARY KEY,
	username VARCHAR(50) NULL, 
	password VARCHAR(50) NULL,
	fullName VARCHAR(75) NOT NULL,
	address VARCHAR(75) NOT NULL, 
	email VARCHAR(75) NOT NULL,
	id_type INT NOT NULL								--FK
);

CREATE TABLE EMPLOYEE_TYPE(
	id INT PRIMARY KEY IDENTITY, 
	type VARCHAR(30) NOT NULL, 
);

CREATE TABLE CABIN(
	id INT PRIMARY KEY IDENTITY, 
	address VARCHAR(75) NOT NULL, 
	email VARCHAR(75) NOT NULL, 
	phone CHAR(9) NOT NULL,
	identifier_employee VARCHAR(50) NOT NULL			--FK
);

CREATE TABLE REGISTRY(
	id INT PRIMARY KEY IDENTITY, 
	date DATE NOT NULL,
	hour TIME NOT NULL,
	phone CHAR(9) NOT NULL,
	identifier_employee VARCHAR(50) NOT NULL,			--FK
	id_cabin INT NOT NULL
);

CREATE TABLE APPOINTMENT(
	id INT PRIMARY KEY IDENTITY, 
	date DATE NOT NULL,
	hour TIME NOT NULL,
	dose VARCHAR(25) NOT NULL, 
	id_cabin INT NOT NULL,								--FK
	dui_citizen CHAR(10) NOT NULL						--FK
);

CREATE TABLE CITIZENxEMPLOYEE(
	dui_citizen CHAR(10) NOT NULL,						--PKFK
	identifier_employee VARCHAR(50) NOT NULL,			--PKFK
);

--PK & FK Section.

-- PK Definition
ALTER TABLE CITIZENxEMPLOYEE ADD PRIMARY KEY (dui_citizen, identifier_employee);

-- FK Definition

-- CITIZEN -> DISEASE
ALTER TABLE DISEASE ADD FOREIGN KEY (dui_citizen) REFERENCES CITIZEN(dui);

-- CITIZEN -> VACCINE 
ALTER TABLE VACCINE ADD FOREIGN KEY (dui_citizen) REFERENCES CITIZEN(dui);
-- EMPLOYEE -> VACCINE 
ALTER TABLE VACCINE ADD FOREIGN KEY (identifier_employee) REFERENCES EMPLOYEE(identifier);

-- VACCINE -> SIDE_EFFECTS
ALTER TABLE SIDE_EFFECT ADD FOREIGN KEY (id_vaccine) REFERENCES VACCINE(id);

-- EMPLOYEE -> CABIN
ALTER TABLE CABIN ADD FOREIGN KEY (identifier_employee) REFERENCES EMPLOYEE(identifier);

-- EMPLOYEE_TYPE -> EMPLOYEE
ALTER TABLE EMPLOYEE ADD FOREIGN KEY (id_type) REFERENCES EMPLOYEE_TYPE(id);

-- EMPLOYEE -> REGISTRY
ALTER TABLE REGISTRY ADD FOREIGN KEY (identifier_employee) REFERENCES EMPLOYEE(identifier);
-- CABIN -> REGISTRY
ALTER TABLE REGISTRY ADD FOREIGN KEY (id_cabin) REFERENCES CABIN(id);

-- CITIZEN -> CITIZENxEMPLOYEE
ALTER TABLE CITIZENxEMPLOYEE ADD FOREIGN KEY (dui_citizen) REFERENCES CITIZEN(dui);
-- EMPLOYEE -> CITIZENxEMPLOYEE
ALTER TABLE CITIZENxEMPLOYEE ADD FOREIGN KEY (identifier_employee) REFERENCES EMPLOYEE(identifier);

-- CITIZEN -> APPOINTMENT 
ALTER TABLE APPOINTMENT ADD FOREIGN KEY (dui_citizen) REFERENCES CITIZEN(dui);
-- CABIN -> APPOINTMENT
ALTER TABLE APPOINTMENT ADD FOREIGN KEY (id_cabin) REFERENCES CABIN(id);

INSERT INTO EMPLOYEE_TYPE VALUES ('Manager');
INSERT INTO EMPLOYEE_TYPE VALUES ('Vaccinator');
INSERT INTO EMPLOYEE_TYPE VALUES ('Supervisor');
INSERT INTO EMPLOYEE_TYPE VALUES ('Organizer');
INSERT INTO EMPLOYEE_TYPE VALUES ('Driver');

INSERT INTO IDENTIFIER VALUES ('None');
INSERT INTO IDENTIFIER VALUES ('Ministry of Education');
INSERT INTO IDENTIFIER VALUES ('Ministry of Health ');
INSERT INTO IDENTIFIER VALUES ('National Civil Police');
INSERT INTO IDENTIFIER VALUES ('Government');
INSERT INTO IDENTIFIER VALUES ('Military');
INSERT INTO IDENTIFIER VALUES ('Journalism');